services:
  dulzia-backend:
    build:
      context: ./backend
      target: dev
    container_name: dulzia-backend
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DEFAULT_URI: "http://localhost"
      DATABASE_URL: "postgresql://dulzia:${DULZIA_DB_PASS}@shared-postgres-db:5432/dulzia?serverVersion=16&charset=utf8"
    networks:
      - shared-network
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - ./backend/public/uploads:/var/www/html/public/uploads

  dulzia-frontend:
    build:
      context: ./frontend
      target: dev
    container_name: dulzia-frontend
    restart: unless-stopped
    networks:
      - shared-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  shared-network:
    name: shared-network
    external: true
