services:
  dulzia-backend:
    build:
      context: ./backend
      target: prod
    container_name: dulzia-backend
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "postgresql://dulzia:${DULZIA_DB_PASS}@shared-postgres-db:5432/dulzia?serverVersion=16&charset=utf8"
    networks:
      - shared-network
    volumes:
      - ./backend/public/uploads:/var/www/html/public/uploads

  dulzia-frontend:
    build:
      context: ./frontend
      target: prod
    container_name: dulzia-frontend
    restart: unless-stopped
    environment:
      PORT: "80"
      BACKEND_UPSTREAM: "http://dulzia-backend:8000"
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    external: true
