<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331194500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE admin_token_id_seq CASCADE');
        $this->addSql('DROP TABLE admin_token');
        $this->addSql('ALTER TABLE admin_user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE admin_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX admin_user_username_key RENAME TO UNIQ_AD8A54A9F85E0677');
        $this->addSql('ALTER TABLE contact_submission ALTER submitted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE contact_submission ALTER email_sent DROP DEFAULT');
        $this->addSql('ALTER TABLE contact_submission ALTER email_sent_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE service ALTER sort_order DROP DEFAULT');
        $this->addSql('ALTER TABLE service ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE service_example ALTER sort_order DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_service_example_service RENAME TO IDX_A168C903ED5CA9E6');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE admin_token_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE admin_token (id INT DEFAULT nextval(\'admin_token_id_seq\'::regclass) NOT NULL, token VARCHAR(128) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX admin_token_token_key ON admin_token (token)');
        $this->addSql('ALTER TABLE admin_user ALTER id SET DEFAULT nextval(\'admin_user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE admin_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_ad8a54a9f85e0677 RENAME TO admin_user_username_key');
        $this->addSql('ALTER TABLE contact_submission ALTER submitted_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE contact_submission ALTER email_sent SET DEFAULT false');
        $this->addSql('ALTER TABLE contact_submission ALTER email_sent_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE service ALTER sort_order SET DEFAULT 0');
        $this->addSql('ALTER TABLE service ALTER is_active SET DEFAULT true');
        $this->addSql('ALTER TABLE service_example ALTER sort_order SET DEFAULT 0');
        $this->addSql('ALTER INDEX idx_a168c903ed5ca9e6 RENAME TO idx_service_example_service');
    }
}
